### ISSUE TITLE
Running from Wine don't work

### ISSUE THREAD

**Issue by zerokol-cmd** [demensdeum/RaidenVideoRipper#74]
1. video preview don't work (just black screen)
2. getting video length don't work printing 10 seconds length  
3. Button `Start` outputs `Error while cutting! Result Code: 1`

**Comment by demensdeum** [comment]
Interesting...

**Comment by demensdeum** [comment]
Probably caused by not so sync duration func of QMediaPlayer, will be fixed in 1.0.1.0

**Comment by demensdeum** [comment]
Fixed in 1.0.1.0
